### ISSUE TITLE
Plugin doesn't work due to Java version incompatibilites.

### ISSUE THREAD

**Issue by leetfin** [CaioFPeres/SkyChunksAndSkyIslands#1]
Hello, I was trying to run this plugin and got the following error. My server is using Java 8 and my hosting provider currently has no option to update. If a version of this could be released that's compatible, that would be great. Thanks!

```
11.12 16:31:03 [Server] ERROR Could not load 'plugins/SkyChunk.jar' in folder 'plugins'
11.12 16:31:03 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: SkyChunk has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 52.0
11.12 16:31:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.4.jar:git-Paper-323]
11.12 16:31:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.4.jar:git-Paper-323]
11.12 16:31:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.4.jar:git-Paper-323]
11.12 16:31:03 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.4.jar:git-Paper-323]
11.12 16:31:03 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-323]
11.12 16:31:03 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-323]
11.12 16:31:03 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-323]
11.12 16:31:03 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
11.12 16:31:03 [Server] INFO Caused by: java.lang.UnsupportedClassVersionError: SkyChunk has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 52.0
11.12 16:31:03 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_275]
11.12 16:31:03 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_275]
11.12 16:31:03 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_275]
11.12 16:31:03 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:178) ~[patched_1.16.4.jar:git-Paper-323]
11.12 16:31:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.4.jar:git-Paper-323]
11.12 16:31:03 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[patched_1.16.4.jar:git-Paper-323]
11.12 16:31:03 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.4.jar:git-Paper-323]
11.12 16:31:03 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
11.12 16:31:03 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
11.12 16:31:03 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_275]
11.12 16:31:03 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_275]
11.12 16:31:03 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.4.jar:git-Paper-323]
11.12 16:31:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.4.jar:git-Paper-323]
11.12 16:31:03 [Server] INFO ... 7 more
```

**Comment by CaioFPeres** [comment]
Sorry, i forgot to take a look at github for some time. I added a version compiled using Java 8 at jar folder. Try it to see if it works.
